config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[new create index show ] do
      get 'comments/new', to: 'comments#new'
      post 'comments/new', to: 'comments#create'
      post 'likes/new', to: 'likes#create'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :id, uniqueness: true
  validates :text, presence: true
  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :post_id, presence: true, numericality: { only_integer: true }

  scope :most_recent, -> { order(created_at: :asc).limit(5) }

  # A method that updates the comments counter for a post.

  def update_comments(num, post_id)
    Post.find_by(id: post_id).update(comments_counter: num)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :id, uniqueness: true
  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :post_id, presence: true, numericality: { only_integer: true }

  # A method that updates the likes counter for a post.

  def update_likes(num, post_id)
    Post.find_by(id: post_id).update(likes_counter: num)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :id, uniqueness: true
  validates :text, presence: true
  validates :title, presence: true, length: { maximum: 250 }
  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :comments_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  # A method that updates the posts counter for a user.

  def update_counter(num, user_id)
    User.find_by(id: user_id).update(posts_counter: num)
  end

  # A method which returns the 5 most recent comments for a given post.

  def recent_comments()
    comments.most_recent
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :id, uniqueness: true
  validates :name, presence: true
  validates :photo, presence: true
  validates :bio, presence: true
  validates :posts_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  # A method that returns the 3 most recent posts for a given user.

  def show_posts()
    posts.order(created_at: :asc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.all.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @newcomment = Comment.new
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    # rubocop:disable Layout
    newcomment = Comment.new(params.require(:comment).permit(:text).merge(created_at: Time.now, updated_at: Time.now, user_id: current_user.id, post_id: params['post_id']))
    # rubocop:enable Layout
    respond_to do |format|
      format.html do
        if newcomment.save
          flash[:success] = 'Comment created successfully'
          redirect_to user_posts_path
        else
          flash.now[:error] = 'Error: Comment could not be created'
          render :new, locals: { newcomment: newcomment }
        end
      end
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find_by(id: params['post_id'])
    flag = false
    post.likes.each do |like|
      flag = true if like.user_id == current_user.id
    end
    return unless flag == false

    newlike = Like.new(created_at: Time.now, updated_at: Time.now, user_id: current_user.id,
                       post_id: params['post_id'])
    respond_to do |format|
      format.html do
        if newlike.save
          flash[:success] = 'Post liked successfully'
          redirect_to user_posts_path
        else
          flash.now[:error] = 'Error: Like could not be created'
        end
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    return unless User.exists?(id: params['user_id'])

    @user = User.includes(posts: %i[likes comments]).find_by(id: params['user_id'])
    render '../views/layouts/partials/_userposts'
  end

  def show
    return unless Post.exists?(id: params['id'])

    @post = Post.includes(:likes, :comments).find_by(id: params['id'])
    if @post.user_id == params['user_id'].to_i
      render '../views/layouts/partials/_userpostdetails'
    else
      render '../views/layouts/partials/_wrongid'
    end
  end

  def new
    if params['user_id'].to_i == current_user.id
      @newpost = Post.new
      respond_to do |format|
        format.html { render :new }
      end
    else
      render '../views/layouts/partials/_wrongid'
    end
  end

  def create
    # rubocop:disable Layout
    newpost = Post.new(params.require(:post).permit(:title, :text).merge(created_at: Time.now, updated_at: Time.now, user_id: current_user.id, comments_counter: 0, likes_counter: 0))
    # rubocop:enable Layout
    respond_to do |format|
      format.html do
        if newpost.save
          flash[:success] = 'Post created successfully'
          redirect_to user_posts_path
        else
          flash.now[:error] = 'Error: Post could not be created'
          render :new, locals: { newpost: newpost }
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show
    return unless User.exists?(id: params['id'])

    @user = User.includes(posts: %i[comments likes]).find_by(id: params['id'])
    render '../views/layouts/partials/_userdetails'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1> Add a comment </h1>
<%= form_with model: @newcomment, url: user_post_comments_new_path, method: :post, local: true, scope: :comment do |f| %>
  <div>
    <%= f.label :Comment %><br>
    <%= f.text_area :text, :required => true %>
  </div>
  <%= f.submit "Add comment" %>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_userdetails.erb
<div class="user-div">
    <img class = "user-image" alt='alt image for <%= @user.name %>' />
    <h2> <%= @user.name %> </h2>
    <h2 class="user-posts"> Number of posts:<%= @user.posts.size %> </h2>
</div>
<div class="user-div">
    <p> <%= @user.bio %> </p>
</div>
<a href = "./posts/new" class="button"> Create new post </a>
<% @user.posts.each do |post| %>
    <div class="user-div">
        <div style="display:flex;flex-flow:column;">
            <a href="/users/<%= @user.id %>/posts/<%= post.id %>">
            <h2> <%= post.title %> </h2></a><br>
            <h3> <%= post.text.first(400) %> </h3>
        </div>
        <p class="user-posts"> Likes:<%= post.likes.size %><br>Comments:<%= post.comments.size %> </p>
    </div>
<% end %>

app/views/layouts/partials/_usermain.erb
<% User.all.each do |user| %>
    <div class="user-div">
        <img class = "user-image" alt='alt image for <%= user.name %>' />
        <a href="/users/<%= user.id %>">
        <h2> <%= user.name %> </h2>
        </a>
        <h2 class="user-posts"> Number of posts:<%= user.posts.size %> </h2>
    </div>
<% end %>

app/views/layouts/partials/_userpostdetails.erb
<div class="user-div">
    <div style="display:flex;flex-flow:column;">
        <h2> <%= @post.title %> </h2><p class="user-posts" style="display:inline-flex;"> Likes:<%= @post.likes.size %><br>Comments:<%= @post.comments.size %> </p>
        <%= link_to 'Like this post', "./#{params['id']}/likes/new", method: 'post', local: true %>
        <h3> <%= @post.text%> </h3>
    </div>
</div>
<div class="comments">
    <h2> Comments </h2>
        <% comments = @post.comments.most_recent %>
        <% comments.each do |comment| %>
            <h3> <%= comment.user.name %> : <%= comment.text %></h3>
        <% end %>
        <a href='./<%= params["id"] %>/comments/new'>Add a new comment</a>
</div>

app/views/layouts/partials/_userposts.erb
<div class="user-div">
    <img class = "user-image" alt='alt image for <%= @user.name %>' />
    <h2> <%= @user.name %> </h2>
    <h2 class="user-posts"> Number of posts:<%= @user.posts.size %> </h2>
</div>
<a href = "./posts/new" class="button"> Create new post </a>
<% @user.posts.each do |post| %>
    <div class="user-div">
        <div style="display:flex;flex-flow:column;">
            <h2><a href="/users/<%= @user.id %>/posts/<%= post.id %>"> <%= post.title %> </a></h2><br>
            <h3> <%= post.text.first(400) %>... </h3>
        </div>
        <p class="user-posts"> Likes:<%= post.likes.size %><br>Comments:<%= post.comments.size %> </p>
    </div>
    <div class="comments">
        <h2> Comments </h2>
            <% comments = post.recent_comments %>
            <% comments.each do |comment| %>
                <h3> <%= comment.user.name %> : <%= comment.text %></h3>
            <% end %>
        </div>
<% end %>

app/views/layouts/partials/_wrongid.erb
<h1> You're not allowed to view this page </h1>

app/views/pages/index.html.erb
<h1> This is the index </h1>
<%= render "layouts/partials/usermain" %>

app/views/posts/index.html.erb
<h1>This is the list of posts for the user with id of <%= params["user_id"] %></h1>

app/views/posts/new.html.erb
<h1> New post </h1>
<%= form_with model: @newpost, url: user_posts_path, method: :post, local: true, scope: :post do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title, :required => true %>
  </div>
  
  <div>
    <%= f.label :text %><br>
    <%= f.text_field :text, :required => true %>
  </div>
  <%= f.submit "Add Post" %>
  
<% end %>

app/views/posts/show.html.erb
<h1> This is the post number <%= params["id"] %> from the user with id <%= params["user_id"] %> </h1>

app/views/users/index.html.erb
<h1>This is the main section for the users</h1>
<%= render "layouts/partials/usermain" %>

app/views/users/show.html.erb
<h1> This is the details page for user with id <%= params["id"] %> </h1>